# Generated by Django 2.0.7 on 2019-03-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(default='s0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('initials', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('workload', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day', models.CharField(choices=[('seg', 'segunda'), ('ter', 'terça'), ('qua', 'quarta'), ('qui', 'quinta'), ('sex', 'sexta'), ('sab', 'sábado'), ('dom', 'domingo')], default='seg', max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='8:00')),
                ('day', models.ManyToManyField(to='app.Day')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.ManyToManyField(to='app.Day'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
