states = {
    's0':{
        'next_state':
        {
            '/start':'s1'
        }
    },
    's1':{
        'next_state':
        {
            '/disciplinas':'s2',
            'Disciplinas':'s2',
            '/ajuda':'s3',
            'Ajuda':'s3',
            '/codigo':'s4',
            'Código':'s4'
        }
    },
    's2':{
        'next_state':
        {
            '/adicionar':'s5',
            'Adicionar':'s5',
            '/remover':'s6',
            'Remover':'s6',
            '/editar':'s7',
            'Editar':'s7',
            '/listar':'s8',
            'Listar':'s8'
        }
    },
    's3':{
        'next_state':
        {
            '/menu':'s1',
            'Menu':'s1',
            '/voltar':'s1',
            'Voltar':'s1'
        }
    },
    's4':{
        'next_state':
        {
            '/menu':'s1',
            'Menu':'s1',
            '/voltar':'s1',
            'Voltar':'s1'
        }
    },
    's5':{
        'next_state':
        {
            '/input':'s5.1',
            '/voltar':'s2',
            'Voltar':'s2'
        },
        '/input':{
            's5.1':'/store_course'
        }
    },
    's5.1':{
        'next_state':
        {
            '/adicionar':'s5',
            'Adicionar':'s5',
            '/menu':'s1',
            'Menu':'s1'
        }
    },
    's6':{
        'next_state':
        {
            '/input':'s6.1',
        },
        '/input':{
            's6.1':'/delete_course'
        }
    },
    's6.1':{
        'next_state':
        {
            '/remover':'s6',
            'Remover':'s6',
            '/menu':'s1',
            'Menu':'s1'
        }
    },
    's7':{
        'next_state':
        {
            '/input':'s7.1',
        },
        '/input':{
            's7.1':'/edit_course_selected'
        }
    },
    's7.1':{
        'next_state':
        {
            'Nº de Faltas':'s7.2',
            'Sigla':'s7.3',
            'Dias e Horários':'s7.4',
            'Nº de Créditos':'s7.5'
        },
    },
    's7.2':{
        'next_state':
        {
            '/input':'s7.6'
        },
        '/input':{
            's7.6':'/edit_number_of_absences'
        }
    },
    's7.3':{
        'next_state':
        {
            '/input':'s7.7'
        },
        '/input':{
            's7.7':'/edit_course_initials'
        }
    },
    's7.4':{
        'next_state':
        {
            '/input':'s7.8'
        },
        '/input':{
            's7.8':'/edit_course_days_and_times'
        }
    },
    's7.5':{
        'next_state':
        {
            '/input':'s7.9'
        },
        '/input':{
            's7.9':'/edit_course_workload'
        }
    },
    's7.6':{
        'next_state':
        {
            '/input':'s7.10'
        },
        '/input':{
            's7.10':'/edit_number_of_absences'
        }
    },
    's7.10':{
        'next_state':
        {
            'Editar':'s7',
            'Menu':'s1'
        }
    },
    's8':{
        'next_state':
        {
            '/menu':'s1',
            'Menu':'s1'
        }
    },
}

handlers = {
    '/start':{
        0:{
            'function':'store_user',
            'arguments':['sender']
        },
        1:{
            'function':'main_menu',
            'arguments':['chat_id']
        }
    },
    '/menu':{
        0:{
            'function':'main_menu',
            'arguments':['chat_id']
        }
    },
    'Menu':{
        0:{
            'function':'main_menu',
            'arguments':['chat_id']
        }
    },
    '/ajuda':{
        0:{
            'function':'help_luciano',
            'arguments':['chat_id']
        }

    },
    'Ajuda':{
        0:{
            'function':'help_luciano',
            'arguments':['chat_id']
        }
    },
    '/codigo':{
        0:{
            'function':'source_code',
            'arguments':['chat_id']
        }
    },
    'Código':{
        0:{
            'function':'source_code',
            'arguments':['chat_id']
        }
    },
    '/disciplinas':{
        0:{
            'function':'courses',
            'arguments':['chat_id']
        }
    },
    'Disciplinas':{
        0:{
            'function':'courses',
            'arguments':['chat_id']
        }
    },
    '/adicionar':{
        0:{
            'function':'add_course_initials',
            'arguments':['chat_id']
        }
    },
    'Adicionar':{
        0:{
            'function':'add_course_initials',
            'arguments':['chat_id']
        }
    },
    '/remover':{
        0:{
            'function':'remove_course',
            'arguments':['sender']
        }
    },
    'Remover':{
        0:{
            'function':'remove_course',
            'arguments':['sender']
        }
    },
    '/store_course':{
        0:{
            'function':'store_course',
            'arguments':['sender', 'input']
        }
    },
    '/delete_course':{
        0:{
            'function':'delete_course',
            'arguments':['sender', 'input']
        }
    },
    '/listar':{
        0:{
            'function':'list_courses',
            'arguments':['sender']
        }
    },
    'Listar':{
        0:{
            'function':'list_courses',
            'arguments':['sender']
        }
    },
    '/editar':{
        0:{
            'function':'edit_course',
            'arguments':['sender']
        }
    },
    'Editar':{
        0:{
            'function':'edit_course',
            'arguments':['sender']
        }
    },
    '/edit_course_selected':{
        0:{
            'function':'edit_course_selected',
            'arguments':['sender', 'input']
        }
    },
    '/edit_course_option_selected':{
        0:{
            'function':'edit_course_option_selected',
            'arguments':['sender', 'input']
        }
    },
    '/edit_course_option_handler':{
        0:{
            'function':'edit_course_option_handler',
            'arguments':['sender', 'input']
        }
    },
    'Nº de Faltas':{
        0:{
            'function':'edit_number_of_absences',
            'arguments':['sender']
        }
    },
    '/edit_number_of_absences':{
        0:{
            'function':'edit_number_of_absences_handler',
            'arguments':['sender', 'input']
        }
    },
    'Sigla':{
        0:{
            'function':'edit_course_initials',
            'arguments':['sender', 'input']
        }
    },
    'Dias e Horários':{
        0:{
            'function':'edit_course_days_and_times',
            'arguments':['sender', 'input']
        }
    },
    'Nº de Créditos':{
        0:{
            'function':'edit_course_workload',
            'arguments':['sender', 'input']
        }
    }
}